# Generated by Skyramp v1.3.11 on 2026-03-16 17:31:00.025625184 +0000 UTC m=+84.219212843
# Command: skyramp generate contract rest http://localhost:8000/api/v1/workspaces/{slug}/projects/ \
# 		--api-schema http://localhost:8000/api/schema/ \
# 		--auth-header X-API-Key \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/plane/plane/apps/api/plane/tests/skyramp \
# 		--overwrite \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

# contract test for /api/v1/workspaces/{slug}/projects/ GET
def test_endpoint_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    slug = "string"

    # Expected Response Body
    expected_endpoint_GET_response_body = r'''{
        "count": 20,
        "extra_stats": null,
        "grouped_by": "state",
        "next_cursor": "20:1:0",
        "next_page_results": true,
        "prev_cursor": "20:0:0",
        "prev_page_results": false,
        "results": [
            {
                "description": "Backend services for the mobile application",
                "id": "550e8400-e29b-41d4-a716-446655440000",
                "identifier": "MAB",
                "name": "Mobile App Backend",
                "network": 2
            }
        ],
        "sub_grouped_by": "priority",
        "total_count": 150,
        "total_pages": 8,
        "total_results": 150
    }'''

    # Execute Request
    endpoint_GET_response = client.send_request(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/",
        method="GET",
        headers=headers,
        path_params={"slug": slug},
        query_params={
            "cursor": None,
            "expand": None,
            "fields": None,
            "order_by": None,
            "per_page": None
        }
    )

    # Generated Assertions
    assert endpoint_GET_response.status_code == 200
    assert skyramp.check_schema(endpoint_GET_response, expected_endpoint_GET_response_body)
    assert skyramp.get_response_value(endpoint_GET_response, "count") is not None
    assert skyramp.get_response_value(endpoint_GET_response, "extra_stats") is not None
    assert skyramp.get_response_value(endpoint_GET_response, "grouped_by") is not None

if __name__ == "__main__":
    test_endpoint_get()
