# Generated by Skyramp v1.3.11 on 2026-03-16 18:57:22.395615682 +0000 UTC m=+188.336181701
# Command: skyramp generate load rest http://localhost:8000/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/progress/ \
# 		--api-schema http://localhost:8000/api/schema/ \
# 		--auth-header X-Api-Key \
# 		--default-duration 5 \
# 		--default-num-threads 1 \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output cycle_progress_load_test.py \
# 		--output-dir /home/runner/work/plane/plane/apps/api/plane/tests/skyramp \
# 		--overwrite \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

load_config = skyramp.LoadTestConfig(
    load_duration=5,
    load_num_threads=1,
    load_target_rps=None,
    load_count=None,
    load_rampup_duration=None,
    load_rampup_interval=None
)
def test_endpoint_get(load_test_config:skyramp.LoadTestConfig=load_config):
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-Api-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    cycle_id = "01c25fa0-268d-4150-85ff-84630c33fded"
    project_id = "86072273-f56e-44c2-b646-54affb54201e"
    slug = "string"

    scenario = skyramp.AsyncScenario(name="scenario")
    # Add Request to Scenario
    endpoint_GET_response = scenario.add_async_request(
        name="endpoint_GET",
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/progress/",
        method="GET",
        headers=headers,
        path_params={
            "cycle_id": cycle_id,
            "project_id": project_id,
            "slug": slug
        },
        expected_code="200"
    )
    result = client.send_scenario(
        scenario,
        load_test_config=load_test_config
    )

    print(
        f"""{{"result": {result.get_overall_status()}}}"""
    )


if __name__ == "__main__":
    test_endpoint_get()
