# Generated by Skyramp v1.3.11 on 2026-03-16 18:57:08.052185072 +0000 UTC m=+173.992751090
# Command: skyramp generate integration rest \
# 		--auth-header X-Api-Key \
# 		--framework pytest \
# 		--language python \
# 		--output cycle_progress_integration_test.py \
# 		--output-dir /home/runner/work/plane/plane/apps/api/plane/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/plane/plane/tests/scenario_cycle_progress_workflow_1741910400.json

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL_localhost = "http://localhost:8000"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    workspaces = "test-workspace-1741910400"

    # Request Body
    endpoint_4_POST_request_body = r'''{
        "name": "Test Workspace 1741910400",
        "slug": "test-workspace-1741910400"
    }'''
    
    # Execute Request
    endpoint_4_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/workspaces/",
        method="POST",
        body=endpoint_4_POST_request_body,
        headers={"X-Api-Key": "SKYRAMP_PLACEHOLDER_TOKEN"}
    )
    # Generated Assertions
    assert endpoint_4_POST_response.status_code == 201

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "identifier": "TPROJ1741",
        "name": "Test Project 1741910400"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/workspaces/{workspaces}/projects/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers={"X-Api-Key": "SKYRAMP_PLACEHOLDER_TOKEN"},
        path_params={"workspaces": workspaces}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "end_date": "2024-01-31",
        "name": "Sprint 1 1741910400",
        "start_date": "2024-01-01"
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/workspaces/{workspaces}/projects/{projects}/cycles/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers={"X-Api-Key": "SKYRAMP_PLACEHOLDER_TOKEN"},
        path_params={
            "projects": skyramp.get_response_value(endpoint_1_POST_response, "id"),
            "workspaces": workspaces
        }
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201

    # Execute Request
    endpoint_3_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/workspaces/{workspaces}/projects/{projects}/cycles/{cycles}/progress/",
        method="GET",
        headers={"X-Api-Key": "SKYRAMP_PLACEHOLDER_TOKEN"},
        path_params={
            "cycles": skyramp.get_response_value(endpoint_2_POST_response, "id"),
            "projects": skyramp.get_response_value(endpoint_1_POST_response, "id"),
            "workspaces": workspaces
        }
    )
    # Generated Assertions
    assert endpoint_3_GET_response.status_code == 200

if __name__ == "__main__":
    test_integration()
