# Generated by Skyramp v1.3.11 on 2026-03-16 18:57:03.449339202 +0000 UTC m=+169.389905220
# Command: skyramp generate smoke rest http://localhost:8000/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/progress/ \
# 		--api-schema http://localhost:8000/api/schema/ \
# 		--auth-header X-Api-Key \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output cycle_progress_smoke_test.py \
# 		--output-dir /home/runner/work/plane/plane/apps/api/plane/tests/skyramp \
# 		--overwrite \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

# smoke test for /api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/progress/ GET
def test_endpoint_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-Api-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    cycle_id = "bf95a655-8bf1-4fb6-b02b-afaa62e4ff1e"
    project_id = "2a50fe59-e1fc-48f6-91ef-0ace08e50325"
    slug = "string"

    # Execute Request
    endpoint_GET_response = client.send_request(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/progress/",
        method="GET",
        headers=headers,
        path_params={
            "cycle_id": cycle_id,
            "project_id": project_id,
            "slug": slug
        }
    )

    # Generated Assertions
    assert endpoint_GET_response.status_code == 200

if __name__ == "__main__":
    test_endpoint_get()
