# Generated by Skyramp v1.3.11 on 2026-03-16 17:31:19.094870505 +0000 UTC m=+103.288458144
# Command: skyramp generate fuzz rest http://localhost:8000/api/v1/workspaces/{slug}/projects/ \
# 		--api-schema http://localhost:8000/api/schema/ \
# 		--auth-header X-API-Key \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/plane/plane/apps/api/plane/tests/skyramp \
# 		--overwrite \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

# fuzz test for /api/v1/workspaces/{slug}/projects/ GET
def test_endpoint_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    slug = "string"

    # Fuzz strategies
    endpoint_get_fuzzed_query = {
        "cursor": "0123456789",
        "expand": "0123456789",
        "fields": "0123456789",
        "order_by": "0123456789",
        "per_page": -10
    }
    # Fuzz status codes
    expected_endpoint_get_fuzzed_query_status_code = {
        "cursor": "401",
        "expand": "401",
        "fields": "401",
        "order_by": "401",
        "per_page": "401"
    }

    # Execute Request
    endpoint_GET_response = client.send_request(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/",
        method="GET",
        headers=headers,
        path_params={"slug": slug},
        query_params={
            "cursor": None,
            "expand": None,
            "fields": None,
            "order_by": None,
            "per_page": None
        },
        expected_code="20x"
    )

    for key in endpoint_get_fuzzed_query:
        query_params = {
            "cursor": None,
            "expand": None,
            "fields": None,
            "order_by": None,
            "per_page": None
        }

        query_params[key] = endpoint_get_fuzzed_query[key]

        # Execute Request
        endpoint_GET_response = client.send_request(
            url=URL,
            path="/api/v1/workspaces/{slug}/projects/",
            method="GET",
            headers=headers,
            path_params={"slug": slug},
            query_params=query_params,
            expected_code=expected_endpoint_get_fuzzed_query_status_code[key],
            description=f'Fuzzing query param { key } to { endpoint_get_fuzzed_query[key] }'
        )

        query_params = {
            "cursor": None,
            "expand": None,
            "fields": None,
            "order_by": None,
            "per_page": None
        }

        query_params[key] = ""

        # Execute Request
        endpoint_GET_response = client.send_request(
            url=URL,
            path="/api/v1/workspaces/{slug}/projects/",
            method="GET",
            headers=headers,
            path_params={"slug": slug},
            query_params=query_params,
            expected_code=expected_endpoint_get_fuzzed_query_status_code[key],
            description=f'Fuzzing query param { key } to ""'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_endpoint_get()
