# Generated by Skyramp v1.3.11 on 2026-03-16 17:31:17.952873738 +0000 UTC m=+102.146461397
# Command: skyramp generate integration rest http://localhost:8000/api/v1/workspaces/{slug}/projects/ \
# 		--api-schema http://localhost:8000/api/schema/ \
# 		--auth-header X-API-Key \
# 		--framework pytest \
# 		--language python \
# 		--output-dir /home/runner/work/plane/plane/apps/api/plane/tests/skyramp \
# 		--overwrite \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    slug = "string"

    # Request Body
    endpoint_POST_request_body = r'''{
            "description": "New project description",
            "identifier": "new-project",
            "name": "New Project",
            "project_lead": "0ec6cfa4-e906-4aad-9390-2df0303a41ce"
        }'''
    
    # Expected Response Body
    expected_endpoint_POST_response_body = r'''{
            "created_at": "2024-01-15T10:30:00Z",
            "description": "Development of the mobile application",
            "id": "550e8400-e29b-41d4-a716-446655440000",
            "identifier": "MAD",
            "name": "Mobile App Development",
            "network": 2,
            "project_lead": "550e8400-e29b-41d4-a716-446655440001",
            "updated_at": "2024-01-15T10:30:00Z"
        }'''
    
    endpoint_POST_multipart_values = [
        skyramp.MultipartParam(
            name="name",
            filename="",
            decoded=False,
            value="New Project"
        ),
        skyramp.MultipartParam(
            name="description",
            filename="",
            decoded=False,
            value="New project description"
        ),
        skyramp.MultipartParam(
            name="identifier",
            filename="",
            decoded=False,
            value="new-project"
        ),
        skyramp.MultipartParam(
            name="project_lead",
            filename="",
            decoded=False,
            value="0ec6cfa4-e906-4aad-9390-2df0303a41ce"
        )
    ]
    # Execute Request
    endpoint_POST_response = client.send_request(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/",
        method="POST",
        body=endpoint_POST_request_body,
        headers=headers,
        path_params={"slug": slug},
        multipart_params=endpoint_POST_multipart_values
    )
    # Generated Assertions
    assert endpoint_POST_response.status_code == 201

    # Expected Response Body
    expected_endpoint_GET_response_body = r'''{
            "count": 20,
            "extra_stats": null,
            "grouped_by": "state",
            "next_cursor": "20:1:0",
            "next_page_results": true,
            "prev_cursor": "20:0:0",
            "prev_page_results": false,
            "results": [{
                "description": "Backend services for the mobile application",
                "id": "550e8400-e29b-41d4-a716-446655440000",
                "identifier": "MAB",
                "name": "Mobile App Backend",
                "network": 2
            }],
            "sub_grouped_by": "priority",
            "total_count": 150,
            "total_pages": 8,
            "total_results": 150
        }'''
    
    # Execute Request
    endpoint_GET_response = client.send_request(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/",
        method="GET",
        headers=headers,
        path_params={"slug": slug},
        query_params={
            "cursor": None,
            "expand": None,
            "fields": None,
            "order_by": None,
            "per_page": None
        }
    )
    # Generated Assertions
    assert endpoint_GET_response.status_code == 200

if __name__ == "__main__":
    test_integration()
