# Generated by Skyramp v1.3.11 on 2026-03-16 17:31:20.24848852 +0000 UTC m=+104.442076159
# Command: skyramp generate load rest http://localhost:8000/api/v1/workspaces/{slug}/projects/ \
# 		--api-schema http://localhost:8000/api/schema/ \
# 		--auth-header X-API-Key \
# 		--default-duration 5 \
# 		--default-num-threads 1 \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/plane/plane/apps/api/plane/tests/skyramp \
# 		--overwrite \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

load_config = skyramp.LoadTestConfig(
    load_duration=5,
    load_num_threads=1,
    load_target_rps=None,
    load_count=None,
    load_rampup_duration=None,
    load_rampup_interval=None
)
def test_endpoint_get(load_test_config:skyramp.LoadTestConfig=load_config):
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    slug = "string"

    scenario = skyramp.AsyncScenario(name="scenario")
    # Add Request to Scenario
    endpoint_GET_response = scenario.add_async_request(
        name="endpoint_GET",
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/",
        method="GET",
        headers=headers,
        path_params={"slug": slug},
        query_params={
            "cursor": None,
            "expand": None,
            "fields": None,
            "order_by": None,
            "per_page": None
        },
        expected_code="200"
    )
    result = client.send_scenario(
        scenario,
        load_test_config=load_test_config
    )

    print(
        f"""{{"result": {result.get_overall_status()}}}"""
    )


if __name__ == "__main__":
    test_endpoint_get()
