# Generated by Skyramp v1.2.0+c41d98f4 on 2026-03-16 14:17:22.425394 -0700 PDT m=+19942.402691209
# Command: skyramp generate integration rest http://localhost:8080/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/transfer-issues/ \
# 		--api-schema http://localhost:8080/api/schema/ \
# 		--auth-header X-Api-Key \
# 		--framework pytest \
# 		--language python \
# 		--output test_integration_transfer_issues.py \
# 		--output-dir /Users/mrugeshmaster/git/plane/apps/api/plane/tests/skyramp \
# 		--overwrite \
# 		--path-params slug=test-workspace,project_id=00000000-0000-0000-0000-000000000001,cycle_id=00000000-0000-0000-0000-000000000002 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = "http://localhost:8080"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-Api-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    cycle_id = "00000000-0000-0000-0000-000000000002"
    project_id = "00000000-0000-0000-0000-000000000001"
    slug = "test-workspace"

    # Request Body
    transfer_issues_POST_request_body = r'''{"new_cycle_id": "0ec6cfa4-e906-4aad-9390-2df0303a41ce"}'''

    # Expected Response Body
    expected_transfer_issues_POST_response_body = r'''{"message": "Success"}'''

    transfer_issues_POST_multipart_values = [
        skyramp.MultipartParam(
            name="new_cycle_id",
            filename="",
            decoded=False,
            value="0ec6cfa4-e906-4aad-9390-2df0303a41ce"
        )
    ]
    # Execute Request
    transfer_issues_POST_response = client.send_request(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/transfer-issues/",
        method="POST",
        body=transfer_issues_POST_request_body,
        headers=headers,
        path_params={
            "cycle_id": cycle_id,
            "project_id": project_id,
            "slug": slug
        },
        multipart_params=transfer_issues_POST_multipart_values
    )
    # Generated Assertions
    assert transfer_issues_POST_response.status_code == 200

if __name__ == "__main__":
    test_integration()
