# Generated by Skyramp v1.2.0+c41d98f4 on 2026-03-16 11:25:26.784299 -0700 PDT m=+12508.865706834
# Command: skyramp generate contract rest http://localhost:8080/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/work-items/ \
# 		--api-schema http://localhost:8080/api/schema/ \
# 		--auth-header X-Api-Key \
# 		--framework pytest \
# 		--language python \
# 		--output test_contract_cycle_issues.py \
# 		--output-dir /Users/mrugeshmaster/git/plane/apps/api/plane/tests/skyramp \
# 		--overwrite \
# 		--path-params slug=test-workspace,project_id=00000000-0000-0000-0000-000000000001,cycle_id=00000000-0000-0000-0000-000000000002 \
# 		--runtime local

# Import of required libraries
import os
import pytest
import skyramp
import requests
from skyramp import MockV2


# URL for test requests
URL = "http://localhost:8000"

# Definition of authentication header
def get_header():
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-Api-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")
    return headers

# contract test for /api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/work-items/ GET
def test_cycle_issues_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = get_header()

    # Declaration of variables
    cycle_id = "00000000-0000-0000-0000-000000000002"
    project_id = "00000000-0000-0000-0000-000000000001"
    slug = "test-workspace"

    # Expected Response Body
    expected_cycle_issues_GET_response_body = r'''{
        "count": 20,
        "extra_stats": null,
        "grouped_by": "state",
        "next_cursor": "20:1:0",
        "next_page_results": true,
        "prev_cursor": "20:0:0",
        "prev_page_results": false,
        "results": [
            {
                "created_at": "2024-01-01T10:30:00Z",
                "cycle": "550e8400-e29b-41d4-a716-446655440001",
                "id": "550e8400-e29b-41d4-a716-446655440000",
                "issue": "550e8400-e29b-41d4-a716-446655440002",
                "sub_issues_count": 3
            }
        ],
        "sub_grouped_by": "priority",
        "total_count": 150,
        "total_pages": 8,
        "total_results": 150
    }'''

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/work-items/",
        method="GET",
        status_code=200,
        response_body=expected_cycle_issues_GET_response_body
    )
    client.apply_mock(mock)

    # Execute Request
    cycle_issues_GET_response = client.send_request(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/work-items/",
        method="GET",
        headers=headers,
        path_params={
            "cycle_id": cycle_id,
            "project_id": project_id,
            "slug": slug
        },
        query_params={
            "cursor": None,
            "per_page": None
        }
    )

    # Generated Assertions
    assert cycle_issues_GET_response.status_code == 200
    assert skyramp.check_schema(cycle_issues_GET_response, expected_cycle_issues_GET_response_body)
    assert skyramp.get_response_value(cycle_issues_GET_response, "count") is not None
    assert skyramp.get_response_value(cycle_issues_GET_response, "extra_stats") is not None
    assert skyramp.get_response_value(cycle_issues_GET_response, "grouped_by") is not None

    client.remove_all_mocks()



# contract test for /api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/work-items/ POST
def test_cycle_issues_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = get_header()

    # Declaration of variables
    cycle_id = "00000000-0000-0000-0000-000000000002"
    project_id = "00000000-0000-0000-0000-000000000001"
    slug = "test-workspace"

    cycle_issues_POST_multipart_values = [
        skyramp.MultipartParam(
            name="issues[0]",
            filename="",
            decoded=False,
            value="0ec6cfa4-e906-4aad-9390-2df0303a41cd"
        ),
        skyramp.MultipartParam(
            name="issues[1]",
            filename="",
            decoded=False,
            value="0ec6cfa4-e906-4aad-9390-2df0303a41ce"
        )
    ]
    # Request Body
    cycle_issues_POST_request_body = r'''{
        "issues": [
            "0ec6cfa4-e906-4aad-9390-2df0303a41cd",
            "0ec6cfa4-e906-4aad-9390-2df0303a41ce"
        ]
    }'''

    # Expected Response Body
    expected_cycle_issues_POST_response_body = r'''{
        "created_at": "2024-01-01T10:30:00Z",
        "cycle": "550e8400-e29b-41d4-a716-446655440001",
        "id": "550e8400-e29b-41d4-a716-446655440000",
        "issue": "550e8400-e29b-41d4-a716-446655440002",
        "sub_issues_count": 3,
        "updated_at": "2024-01-10T15:45:00Z"
    }'''

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/work-items/",
        method="POST",
        status_code=200,
        request_body=cycle_issues_POST_request_body,
        response_body=expected_cycle_issues_POST_response_body
    )
    client.apply_mock(mock)

    # Execute Request
    cycle_issues_POST_response = client.send_request(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/work-items/",
        method="POST",
        body=cycle_issues_POST_request_body,
        headers=headers,
        path_params={
            "cycle_id": cycle_id,
            "project_id": project_id,
            "slug": slug
        },
        multipart_params=cycle_issues_POST_multipart_values
    )

    # Generated Assertions
    assert cycle_issues_POST_response.status_code == 200
    assert skyramp.check_schema(cycle_issues_POST_response, expected_cycle_issues_POST_response_body)
    assert skyramp.get_response_value(cycle_issues_POST_response, "created_at") is not None
    assert skyramp.get_response_value(cycle_issues_POST_response, "cycle") is not None
    assert skyramp.get_response_value(cycle_issues_POST_response, "id") is not None

    client.remove_all_mocks()



# contract test for /api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/work-items/{issue_id}/ GET
def test_issue_id_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = get_header()

    # Declaration of variables
    cycle_id = "00000000-0000-0000-0000-000000000002"
    issue_id = "af816b47-a5d7-4cba-bedc-8196bdc6b077"
    project_id = "00000000-0000-0000-0000-000000000001"
    slug = "test-workspace"

    # Expected Response Body
    expected_issue_id_GET_response_body = r'''{
        "created_at": "2024-01-01T10:30:00Z",
        "cycle": "550e8400-e29b-41d4-a716-446655440001",
        "id": "550e8400-e29b-41d4-a716-446655440000",
        "issue": "550e8400-e29b-41d4-a716-446655440002",
        "sub_issues_count": 3,
        "updated_at": "2024-01-10T15:45:00Z"
    }'''

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/work-items/{issue_id}/",
        method="GET",
        status_code=200,
        response_body=expected_issue_id_GET_response_body
    )
    client.apply_mock(mock)

    # Execute Request
    issue_id_GET_response = client.send_request(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/work-items/{issue_id}/",
        method="GET",
        headers=headers,
        path_params={
            "cycle_id": cycle_id,
            "issue_id": issue_id,
            "project_id": project_id,
            "slug": slug
        }
    )

    # Generated Assertions
    assert issue_id_GET_response.status_code == 200
    assert skyramp.check_schema(issue_id_GET_response, expected_issue_id_GET_response_body)
    assert skyramp.get_response_value(issue_id_GET_response, "created_at") is not None
    assert skyramp.get_response_value(issue_id_GET_response, "cycle") is not None
    assert skyramp.get_response_value(issue_id_GET_response, "id") is not None

    client.remove_all_mocks()



# contract test for /api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/work-items/{issue_id}/ DELETE
def test_issue_id_delete():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = get_header()

    # Declaration of variables
    cycle_id = "00000000-0000-0000-0000-000000000002"
    issue_id = "858fb8f9-afed-4028-93ad-358aa535e9ae"
    project_id = "00000000-0000-0000-0000-000000000001"
    slug = "test-workspace"

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/work-items/{issue_id}/",
        method="DELETE",
        status_code=204
    )
    client.apply_mock(mock)

    # Execute Request
    issue_id_DELETE_response = client.send_request(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/work-items/{issue_id}/",
        method="DELETE",
        headers=headers,
        path_params={
            "cycle_id": cycle_id,
            "issue_id": issue_id,
            "project_id": project_id,
            "slug": slug
        }
    )

    # Generated Assertions
    assert issue_id_DELETE_response.status_code == 204

    client.remove_all_mocks()


if __name__ == "__main__":
    test_cycle_issues_get()
    test_cycle_issues_post()
    test_issue_id_get()
    test_issue_id_delete()
