# Generated by Skyramp v1.3.13 on 2026-03-19 21:54:01.622330474 +0000 UTC m=+122.718448357
# Command: skyramp generate integration rest \
# 		--auth-header X-Api-Key \
# 		--framework pytest \
# 		--language python \
# 		--output test_integration_workspace_stats.py \
# 		--output-dir /home/runner/work/plane-mrugesh-0316/plane-mrugesh-0316/apps/api/plane/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/plane-mrugesh-0316/plane-mrugesh-0316/apps/api/plane/tests/skyramp/scenario_workspace-stats-get.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-Api-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    workspaces = "test-workspace"

    # Execute Request
    endpoint_1_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/workspaces/{workspaces}/stats/",
        method="GET",
        headers={"X-Api-Key": ""},
        path_params={"workspaces": workspaces}
    )
    # Generated Assertions
    assert endpoint_1_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
