# Generated by Skyramp v1.3.11 on 2026-03-16 21:03:47.461058675 +0000 UTC m=+102.826247195
# Command: skyramp generate integration rest http://localhost:8000/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/archive/ \
# 		--api-schema http://localhost:8000/api/schema/ \
# 		--auth-header X-API-Key \
# 		--framework pytest \
# 		--language python \
# 		--output test_integration_cycle_archive.py \
# 		--output-dir /home/runner/work/plane/plane/apps/api/plane/tests/skyramp \
# 		--overwrite \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    cycle_id = "b8d9c3b4-546a-4820-b4ee-fc7f06a9b36e"
    project_id = "e8909c01-cacc-4caf-a2ee-dcdd89a76142"
    slug = "string"

    # Execute Request
    endpoint_POST_response = client.send_request(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/archive/",
        method="POST",
        headers=headers,
        path_params={
            "cycle_id": cycle_id,
            "project_id": project_id,
            "slug": slug
        }
    )
    # Generated Assertions
    assert endpoint_POST_response.status_code == 204

if __name__ == "__main__":
    test_integration()
