# Generated by Skyramp v1.3.13 on 2026-03-19 21:53:56.655183425 +0000 UTC m=+117.751301327
# Command: skyramp generate contract rest http://localhost:8000/api/v1/workspaces/test-workspace/stats/ \
# 		--auth-header X-Api-Key \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_contract_workspace_stats.py \
# 		--output-dir /home/runner/work/plane-mrugesh-0316/plane-mrugesh-0316/apps/api/plane/tests/skyramp \
# 		--overwrite \
# 		--path-params slug=test-workspace \
# 		--provider \
# 		--response-data {"workspace_id":"550e8400-e29b-41d4-a716-446655440000","workspace_slug":"test-workspace","workspace_name":"Test Workspace","total_projects":5,"total_issues":42,"total_members":3,"created_at":"2024-01-01T10:30:00Z"} \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/workspaces/test-workspace/stats/ GET
def test_stats_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-Api-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_stats_GET_response_body = r'''{
        "created_at": "2024-01-01T10:30:00Z",
        "total_issues": 42,
        "total_members": 3,
        "total_projects": 5,
        "workspace_id": "550e8400-e29b-41d4-a716-446655440000",
        "workspace_name": "Test Workspace",
        "workspace_slug": "test-workspace"
    }'''

    # Execute Request
    stats_GET_response = client.send_request(
        url=URL,
        path="/api/v1/workspaces/test-workspace/stats/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(stats_GET_response, "20x")
    assert skyramp.check_schema(stats_GET_response, expected_stats_GET_response_body)
    assert skyramp.get_response_value(stats_GET_response, "created_at") is not None
    assert skyramp.get_response_value(stats_GET_response, "total_issues") is not None
    assert skyramp.get_response_value(stats_GET_response, "total_members") is not None


if __name__ == "__main__":
    test_stats_get()
