# Generated by Skyramp v1.3.11 on 2026-03-16 21:01:57.144277505 +0000 UTC m=+191.483335816
# Command: skyramp generate integration rest http://localhost:8000/api/v1/workspaces/{slug}/projects/{project_id}/cycles/ \
# 		--api-schema http://localhost:8000/api/schema/ \
# 		--auth-header X-API-Key \
# 		--framework pytest \
# 		--language python \
# 		--output test_integration_cycle_overdue_issues.py \
# 		--output-dir /home/runner/work/plane/plane/apps/api/plane/tests/skyramp \
# 		--overwrite \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    project_id = "0b95ffc6-eb97-4ee0-81c7-940c7b6c53df"
    slug = "string"

    # Request Body
    endpoint_POST_request_body = r'''{
            "description": "Cycle 1 description",
            "end_date": "2021-01-31",
            "external_id": "1234567890",
            "external_source": "github",
            "name": "Cycle 1",
            "start_date": "2021-01-01"
        }'''
    
    # Expected Response Body
    expected_endpoint_POST_response_body = r'''{
            "backlog_issues": 0,
            "cancelled_issues": 1,
            "completed_issues": 8,
            "created_at": "2024-01-01T10:30:00Z",
            "description": "First sprint of the quarter focusing on core features",
            "end_date": "2024-01-14",
            "id": "550e8400-e29b-41d4-a716-446655440000",
            "name": "Sprint 1 - Q1 2024",
            "start_date": "2024-01-01",
            "started_issues": 4,
            "status": "current",
            "total_issues": 15,
            "unstarted_issues": 2,
            "updated_at": "2024-01-10T15:45:00Z"
        }'''
    
    endpoint_POST_multipart_values = [
        skyramp.MultipartParam(
            name="description",
            filename="",
            decoded=False,
            value="Cycle 1 description"
        ),
        skyramp.MultipartParam(
            name="start_date",
            filename="",
            decoded=False,
            value="2021-01-01"
        ),
        skyramp.MultipartParam(
            name="end_date",
            filename="",
            decoded=False,
            value="2021-01-31"
        ),
        skyramp.MultipartParam(
            name="external_id",
            filename="",
            decoded=False,
            value="1234567890"
        ),
        skyramp.MultipartParam(
            name="external_source",
            filename="",
            decoded=False,
            value="github"
        ),
        skyramp.MultipartParam(
            name="name",
            filename="",
            decoded=False,
            value="Cycle 1"
        )
    ]
    # Execute Request
    endpoint_POST_response = client.send_request(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/{project_id}/cycles/",
        method="POST",
        body=endpoint_POST_request_body,
        headers=headers,
        path_params={
            "project_id": project_id,
            "slug": slug
        },
        multipart_params=endpoint_POST_multipart_values
    )
    # Generated Assertions
    assert endpoint_POST_response.status_code == 201

    # Expected Response Body
    expected_endpoint_GET_response_body = r'''{
            "count": 20,
            "extra_stats": null,
            "grouped_by": "state",
            "next_cursor": "20:1:0",
            "next_page_results": true,
            "prev_cursor": "20:0:0",
            "prev_page_results": false,
            "results": [{
                "description": "First sprint of the quarter focusing on core features",
                "end_date": "2024-01-14",
                "id": "550e8400-e29b-41d4-a716-446655440000",
                "name": "Sprint 1 - Q1 2024",
                "start_date": "2024-01-01",
                "status": "current"
            }],
            "sub_grouped_by": "priority",
            "total_count": 150,
            "total_pages": 8,
            "total_results": 150
        }'''
    
    # Execute Request
    endpoint_GET_response = client.send_request(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/{project_id}/cycles/",
        method="GET",
        headers=headers,
        path_params={
            "project_id": project_id,
            "slug": slug
        },
        query_params={
            "cursor": None,
            "cycle_view": None,
            "expand": None,
            "fields": None,
            "order_by": None,
            "per_page": None
        }
    )
    # Generated Assertions
    assert endpoint_GET_response.status_code == 200

if __name__ == "__main__":
    test_integration()
