# Generated by Skyramp v1.3.11 on 2026-03-16 21:39:45.365390665 +0000 UTC m=+96.824156780
# Command: skyramp generate smoke rest http://localhost:8000/api/v1/workspaces/{slug}/projects/{project_id}/summary/ \
# 		--api-schema http://localhost:8000/api/schema/ \
# 		--auth-header X-Api-Key \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_smoke_project_summary_open_issues.py \
# 		--output-dir /home/runner/work/plane/plane/apps/api/plane/tests/skyramp \
# 		--overwrite \
# 		--path-params slug=test-workspace,project_id=00000000-0000-0000-0000-000000000001 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

# smoke test for /api/v1/workspaces/{slug}/projects/{project_id}/summary/ GET
def test_endpoint_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-Api-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    project_id = "00000000-0000-0000-0000-000000000001"
    slug = "test-workspace"

    # Execute Request
    endpoint_GET_response = client.send_request(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/{project_id}/summary/",
        method="GET",
        headers=headers,
        path_params={
            "project_id": project_id,
            "slug": slug
        }
    )

    # Generated Assertions
    assert endpoint_GET_response.status_code == 200

if __name__ == "__main__":
    test_endpoint_get()
