# Generated by Skyramp v1.2.0+c41d98f4 on 2026-03-16 11:25:04.319407 -0700 PDT m=+12486.400851334
# Command: skyramp generate integration rest http://localhost:8080/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/cycle-issues/ \
# 		--api-schema http://localhost:8080/api/schema/ \
# 		--auth-header X-Api-Key \
# 		--chaining-key issue_id \
# 		--framework pytest \
# 		--language python \
# 		--output test_integration_cycle_issues.py \
# 		--output-dir /Users/mrugeshmaster/git/plane/apps/api/plane/tests/skyramp \
# 		--overwrite \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = "http://localhost:8000"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-Api-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    cycle_id = "55c6afec-9c19-4feb-9103-3c1a1339e08d"
    project_id = "43b77669-b41a-41fe-b143-2d64269d6bb0"
    slug = "string"

    # Request Body
    cycle_issues_POST_request_body = r'''{"issues": [
                "0ec6cfa4-e906-4aad-9390-2df0303a41cd",
                    "0ec6cfa4-e906-4aad-9390-2df0303a41ce"
            ]}'''

    # Expected Response Body
    expected_cycle_issues_POST_response_body = r'''{
            "created_at": "2024-01-01T10:30:00Z",
            "cycle": "550e8400-e29b-41d4-a716-446655440001",
            "id": "550e8400-e29b-41d4-a716-446655440000",
            "issue": "550e8400-e29b-41d4-a716-446655440002",
            "sub_issues_count": 3,
            "updated_at": "2024-01-10T15:45:00Z"
        }'''

    cycle_issues_POST_multipart_values = [
        skyramp.MultipartParam(
            name="issues[0]",
            filename="",
            decoded=False,
            value="0ec6cfa4-e906-4aad-9390-2df0303a41cd"
        ),
        skyramp.MultipartParam(
            name="issues[1]",
            filename="",
            decoded=False,
            value="0ec6cfa4-e906-4aad-9390-2df0303a41ce"
        )
    ]
    # Execute Request
    cycle_issues_POST_response = client.send_request(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/cycle-issues/",
        method="POST",
        body=cycle_issues_POST_request_body,
        headers=headers,
        path_params={
            "cycle_id": cycle_id,
            "project_id": project_id,
            "slug": slug
        },
        multipart_params=cycle_issues_POST_multipart_values
    )
    # Generated Assertions
    assert cycle_issues_POST_response.status_code == 200

    # Expected Response Body
    expected_cycle_issues_GET_response_body = r'''{
            "count": 20,
            "extra_stats": null,
            "grouped_by": "state",
            "next_cursor": "20:1:0",
            "next_page_results": true,
            "prev_cursor": "20:0:0",
            "prev_page_results": false,
            "results": [{
                "created_at": "2024-01-01T10:30:00Z",
                "cycle": "550e8400-e29b-41d4-a716-446655440001",
                "id": "550e8400-e29b-41d4-a716-446655440000",
                "issue": "550e8400-e29b-41d4-a716-446655440002",
                "sub_issues_count": 3
            }],
            "sub_grouped_by": "priority",
            "total_count": 150,
            "total_pages": 8,
            "total_results": 150
        }'''

    # Execute Request
    cycle_issues_GET_response = client.send_request(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/cycle-issues/",
        method="GET",
        headers=headers,
        path_params={
            "cycle_id": cycle_id,
            "project_id": project_id,
            "slug": slug
        },
        query_params={
            "cursor": None,
            "per_page": None
        }
    )
    # Generated Assertions
    assert cycle_issues_GET_response.status_code == 200

if __name__ == "__main__":
    test_integration()
