# Generated by Skyramp v1.2.0+c41d98f4 on 2026-03-16 14:17:20.316166 -0700 PDT m=+19940.293463417
# Command: skyramp generate contract rest http://localhost:8080/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/transfer-issues/ \
# 		--api-schema http://localhost:8080/api/schema/ \
# 		--auth-header X-Api-Key \
# 		--framework pytest \
# 		--language python \
# 		--output test_contract_transfer_issues.py \
# 		--output-dir /Users/mrugeshmaster/git/plane/apps/api/plane/tests/skyramp \
# 		--overwrite \
# 		--path-params slug=test-workspace,project_id=00000000-0000-0000-0000-000000000001,cycle_id=00000000-0000-0000-0000-000000000002 \
# 		--runtime local

# Import of required libraries
import os
import pytest
import skyramp
import requests
from skyramp import MockV2


# URL for test requests
URL = "http://localhost:8080"

# contract test for /api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/transfer-issues/ POST
def test_transfer_issues_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-Api-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    cycle_id = "00000000-0000-0000-0000-000000000002"
    project_id = "00000000-0000-0000-0000-000000000001"
    slug = "test-workspace"

    transfer_issues_POST_multipart_values = [
        skyramp.MultipartParam(
            name="new_cycle_id",
            filename="",
            decoded=False,
            value="0ec6cfa4-e906-4aad-9390-2df0303a41ce"
        )
    ]
    # Request Body
    transfer_issues_POST_request_body = r'''{
        "new_cycle_id": "0ec6cfa4-e906-4aad-9390-2df0303a41ce"
    }'''

    # Expected Response Body
    expected_transfer_issues_POST_response_body = r'''{
        "message": "Success"
    }'''

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/transfer-issues/",
        method="POST",
        status_code=200,
        request_body=transfer_issues_POST_request_body,
        response_body=expected_transfer_issues_POST_response_body
    )
    client.apply_mock(mock)

    # Execute Request
    transfer_issues_POST_response = client.send_request(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/transfer-issues/",
        method="POST",
        body=transfer_issues_POST_request_body,
        headers=headers,
        path_params={
            "cycle_id": cycle_id,
            "project_id": project_id,
            "slug": slug
        },
        multipart_params=transfer_issues_POST_multipart_values
    )

    # Generated Assertions
    assert transfer_issues_POST_response.status_code == 200
    assert skyramp.check_schema(transfer_issues_POST_response, expected_transfer_issues_POST_response_body)
    assert skyramp.get_response_value(transfer_issues_POST_response, "message") is not None

    client.remove_all_mocks()


if __name__ == "__main__":
    test_transfer_issues_post()
