# Generated by Skyramp v1.3.11 on 2026-03-16 21:26:46.002582291 +0000 UTC m=+132.889185705
# Command: skyramp generate load rest http://localhost:8000/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/archive/ \
# 		--api-schema http://localhost:8000/api/schema/ \
# 		--auth-header X-Api-Key \
# 		--default-duration 5 \
# 		--default-num-threads 1 \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_load_cycle_archive.py \
# 		--output-dir /home/runner/work/plane/plane/apps/api/plane/tests/skyramp \
# 		--overwrite \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

load_config = skyramp.LoadTestConfig(
    load_duration=5,
    load_num_threads=1,
    load_target_rps=None,
    load_count=None,
    load_rampup_duration=None,
    load_rampup_interval=None
)
def test_endpoint_post(load_test_config:skyramp.LoadTestConfig=load_config):
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-Api-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    cycle_id = "239ac909-9c41-4c8c-927c-44a67c6347df"
    project_id = "392f9693-750f-4ad2-9184-899afaf6a7e6"
    slug = "string"

    scenario = skyramp.AsyncScenario(name="scenario")
    # Add Request to Scenario
    endpoint_POST_response = scenario.add_async_request(
        name="endpoint_POST",
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/archive/",
        method="POST",
        headers=headers,
        path_params={
            "cycle_id": cycle_id,
            "project_id": project_id,
            "slug": slug
        },
        expected_code="204"
    )
    result = client.send_scenario(
        scenario,
        load_test_config=load_test_config
    )

    print(
        f"""{{"result": {result.get_overall_status()}}}"""
    )


if __name__ == "__main__":
    test_endpoint_post()
