# Generated by Skyramp v1.3.11 on 2026-03-16 21:03:49.562947033 +0000 UTC m=+104.928135533
# Command: skyramp generate smoke rest http://localhost:8000/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/archive/ \
# 		--api-schema http://localhost:8000/api/schema/ \
# 		--auth-header X-API-Key \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_smoke_cycle_archive.py \
# 		--output-dir /home/runner/work/plane/plane/apps/api/plane/tests/skyramp \
# 		--overwrite \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

# smoke test for /api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/archive/ POST
def test_endpoint_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    cycle_id = "55d7c77d-59a0-4ee1-88a2-0d1fd5e0035d"
    project_id = "83fe62c7-061a-47b4-93cd-f0278d24cf9d"
    slug = "string"

    # Execute Request
    endpoint_POST_response = client.send_request(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/archive/",
        method="POST",
        headers=headers,
        path_params={
            "cycle_id": cycle_id,
            "project_id": project_id,
            "slug": slug
        }
    )

    # Generated Assertions
    assert endpoint_POST_response.status_code == 204

if __name__ == "__main__":
    test_endpoint_post()
