# Generated by Skyramp v1.2.0+c41d98f4 on 2026-03-16 14:11:42.482839 -0700 PDT m=+19602.460280917
# Command: skyramp generate contract rest http://localhost:8080/api/v1/workspaces/{slug}/projects/{project_id}/summary/ \
# 		--api-schema http://localhost:8080/api/schema/ \
# 		--auth-header X-Api-Key \
# 		--framework pytest \
# 		--language python \
# 		--output test_contract_project_summary.py \
# 		--output-dir /Users/mrugeshmaster/git/plane/apps/api/plane/tests/skyramp \
# 		--overwrite \
# 		--path-params slug=test-workspace,project_id=00000000-0000-0000-0000-000000000001 \
# 		--runtime local

# Import of required libraries
import os
import pytest
import skyramp
import requests
from skyramp import MockV2


# URL for test requests
URL = "http://localhost:8080"

# contract test for /api/v1/workspaces/{slug}/projects/{project_id}/summary/ GET
def test_summary_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-Api-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    project_id = "00000000-0000-0000-0000-000000000001"
    slug = "test-workspace"

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/{project_id}/summary/",
        method="GET",
        status_code=200
    )
    client.apply_mock(mock)

    # Execute Request
    summary_GET_response = client.send_request(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/{project_id}/summary/",
        method="GET",
        headers=headers,
        path_params={
            "project_id": project_id,
            "slug": slug
        }
    )

    # Generated Assertions
    assert summary_GET_response.status_code == 200
    assert skyramp.get_response_value(summary_GET_response, "open_issues") is not None

    client.remove_all_mocks()


if __name__ == "__main__":
    test_summary_get()
