# Generated by Skyramp v1.3.11 on 2026-03-16 20:28:54.96117345 +0000 UTC m=+139.467832338
# Command: skyramp generate integration rest http://localhost:8000/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/cycle-issues/ \
# 		--api-schema http://localhost:8000/api/schema/ \
# 		--auth-header X-API-Key \
# 		--chaining-key issue_id \
# 		--framework pytest \
# 		--language python \
# 		--output test_integration_cycle_progress.py \
# 		--output-dir /home/runner/work/plane/plane/apps/api/plane/tests/skyramp \
# 		--overwrite \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    cycle_id = "310dff59-a521-4599-b535-b707f7b87c18"
    project_id = "fa8dd1ae-39ab-4bb6-8862-3200c418269b"
    slug = "string"

    # Request Body
    endpoint_POST_request_body = r'''{"issues": [
                "0ec6cfa4-e906-4aad-9390-2df0303a41cd",
                    "0ec6cfa4-e906-4aad-9390-2df0303a41ce"
            ]}'''
    
    # Expected Response Body
    expected_endpoint_POST_response_body = r'''{
            "created_at": "2024-01-01T10:30:00Z",
            "cycle": "550e8400-e29b-41d4-a716-446655440001",
            "id": "550e8400-e29b-41d4-a716-446655440000",
            "issue": "550e8400-e29b-41d4-a716-446655440002",
            "sub_issues_count": 3,
            "updated_at": "2024-01-10T15:45:00Z"
        }'''
    
    endpoint_POST_multipart_values = [
        skyramp.MultipartParam(
            name="issues[0]",
            filename="",
            decoded=False,
            value="0ec6cfa4-e906-4aad-9390-2df0303a41cd"
        ),
        skyramp.MultipartParam(
            name="issues[1]",
            filename="",
            decoded=False,
            value="0ec6cfa4-e906-4aad-9390-2df0303a41ce"
        )
    ]
    # Execute Request
    endpoint_POST_response = client.send_request(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/cycle-issues/",
        method="POST",
        body=endpoint_POST_request_body,
        headers=headers,
        path_params={
            "cycle_id": cycle_id,
            "project_id": project_id,
            "slug": slug
        },
        multipart_params=endpoint_POST_multipart_values
    )
    # Generated Assertions
    assert endpoint_POST_response.status_code == 200

    # Expected Response Body
    expected_endpoint_GET_response_body = r'''{
            "count": 20,
            "extra_stats": null,
            "grouped_by": "state",
            "next_cursor": "20:1:0",
            "next_page_results": true,
            "prev_cursor": "20:0:0",
            "prev_page_results": false,
            "results": [{
                "created_at": "2024-01-01T10:30:00Z",
                "cycle": "550e8400-e29b-41d4-a716-446655440001",
                "id": "550e8400-e29b-41d4-a716-446655440000",
                "issue": "550e8400-e29b-41d4-a716-446655440002",
                "sub_issues_count": 3
            }],
            "sub_grouped_by": "priority",
            "total_count": 150,
            "total_pages": 8,
            "total_results": 150
        }'''
    
    # Execute Request
    endpoint_GET_response = client.send_request(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/cycle-issues/",
        method="GET",
        headers=headers,
        path_params={
            "cycle_id": cycle_id,
            "project_id": project_id,
            "slug": slug
        },
        query_params={
            "cursor": None,
            "per_page": None
        }
    )
    # Generated Assertions
    assert endpoint_GET_response.status_code == 200

if __name__ == "__main__":
    test_integration()
