# Generated by Skyramp v1.3.11 on 2026-03-16 20:29:10.100512641 +0000 UTC m=+154.607171520
# Command: skyramp generate fuzz rest http://localhost:8000/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/progress/ \
# 		--api-schema http://localhost:8000/api/schema/ \
# 		--auth-header X-API-Key \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_fuzz_cycle_progress.py \
# 		--output-dir /home/runner/work/plane/plane/apps/api/plane/tests/skyramp \
# 		--overwrite \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

# fuzz test for /api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/progress/ GET
def test_endpoint_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    cycle_id = "0b93d215-5de8-4bd6-8771-e8d2a9dd9ec1"
    project_id = "8b398464-1909-4c26-928a-f894a26feced"
    slug = "string"

    # Execute Request
    endpoint_GET_response = client.send_request(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/progress/",
        method="GET",
        headers=headers,
        path_params={
            "cycle_id": cycle_id,
            "project_id": project_id,
            "slug": slug
        },
        expected_code="20x"
    )

    assert client.is_success()


if __name__ == "__main__":
    test_endpoint_get()
