# Generated by Skyramp v1.3.11 on 2026-03-16 21:02:11.297822456 +0000 UTC m=+205.636880747
# Command: skyramp generate fuzz rest http://localhost:8000/api/v1/workspaces/{slug}/projects/{project_id}/cycles/ \
# 		--auth-header X-API-Key \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_fuzz_cycle_overdue_issues.py \
# 		--output-dir /home/runner/work/plane/plane/apps/api/plane/tests/skyramp \
# 		--overwrite \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

# fuzz test for /api/v1/workspaces/{slug}/projects/{project_id}/cycles/ GET
def test_endpoint_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    project_id = "project_id"
    slug = "slug"

    # Execute Request
    endpoint_GET_response = client.send_request(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/{project_id}/cycles/",
        method="GET",
        headers=headers,
        path_params={
            "project_id": project_id,
            "slug": slug
        },
        expected_code="20x"
    )

    assert client.is_success()


if __name__ == "__main__":
    test_endpoint_get()
