# Generated by Skyramp v1.3.11 on 2026-03-16 20:28:43.419862441 +0000 UTC m=+127.926521316
# Command: skyramp generate smoke rest http://localhost:8000/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/progress/ \
# 		--api-schema http://localhost:8000/api/schema/ \
# 		--auth-header X-API-Key \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_smoke_cycle_progress.py \
# 		--output-dir /home/runner/work/plane/plane/apps/api/plane/tests/skyramp \
# 		--overwrite \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:8000"

# smoke test for /api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/progress/ GET
def test_endpoint_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-API-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    cycle_id = "5eab36b3-17cb-4ccc-b1d3-439e7c3f2bfd"
    project_id = "07318c29-9083-44ad-b62a-807eae4d06a0"
    slug = "string"

    # Execute Request
    endpoint_GET_response = client.send_request(
        url=URL,
        path="/api/v1/workspaces/{slug}/projects/{project_id}/cycles/{cycle_id}/progress/",
        method="GET",
        headers=headers,
        path_params={
            "cycle_id": cycle_id,
            "project_id": project_id,
            "slug": slug
        }
    )

    # Generated Assertions
    assert endpoint_GET_response.status_code == 200

if __name__ == "__main__":
    test_endpoint_get()
