# Generated by Skyramp v1.3.13 on 2026-03-16 17:44:52.081498002 +0000 UTC m=+241.576189109
# Command: skyramp generate contract rest http://localhost:8000/api/v1/workspaces/test-workspace-1741910400/projects/cccccccc-0000-0000-0000-000000000001/cycles/dddddddd-0000-0000-0000-000000000001/progress/ \
# 		--auth-header X-Api-Key \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_cycle_progress_contract.py \
# 		--output-dir /home/runner/work/plane/plane/tests \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8000")

# contract test for /api/v1/workspaces/test-workspace-1741910400/projects/cccccccc-0000-0000-0000-000000000001/cycles/dddddddd-0000-0000-0000-000000000001/progress/ GET
def test_progress_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["X-Api-Key"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    progress_GET_response = client.send_request(
        url=URL,
        path="/api/v1/workspaces/test-workspace-1741910400/projects/cccccccc-0000-0000-0000-000000000001/cycles/dddddddd-0000-0000-0000-000000000001/progress/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert progress_GET_response.status_code == 200


if __name__ == "__main__":
    test_progress_get()
